
export const AUTH_TYPE = {
    GETALL: {
        FETCH: 'GETALL_FETCH',
        SUCCESS: 'GETALL_FETCH_SUCCESS',
        FAILURE: 'GETALL_FETCH_FAILURE',
    },
    SIGNIN: {
        FETCH: 'SIGNIN_FETCH',
        SUCCESS: 'SIGNIN_FETCH_SUCCESS',
        FAILURE: 'SIGNIN_FETCH_FAILURE',
    },
    SIGNUP: {
        FETCH: 'SIGNUP_FETCH',
        SUCCESS: 'SIGNUP_FETCH_SUCCESS',
        FAILURE: 'SIGNUP_FETCH_FAILURE',
    },
    CONFIRMCODE: {
        FETCH: 'CONFIRMCODE_FETCH',
        SUCCESS: 'CONFIRMCODE_FETCH_SUCCESS',
        FAILURE: 'CONFIRMCODE_FETCH_FAILURE',
    },
    SIGNEDIN: {
        FETCH: 'SIGNEDIN_FETCH',
        SUCCESS: 'SIGNEDIN_FETCH_SUCCESS',
        FAILURE: 'ISSIGNEDIN_FETCH_FAILURE',
    },
    FORGOTPASSWORD: {
        FETCH: 'FORGOTPASSWORD_FETCH',
        SUCCESS: 'FORGOTPASSWORD_FETCH_SUCCESS',
        FAILURE: 'FORGOTPASSWORD_FETCH_FAILURE',
    },
    CONFIRMFORGOTPASSWORD: {
        FETCH: 'CONFIRMFORGOTPASSWORD_FETCH',
        SUCCESS: 'CONFIRMFORGOTPASSWORD_FETCH_SUCCESS',
        FAILURE: 'CONFIRMFORGOTPASSWORD_FETCH_FAILURE',
    },
    RESET: {
        FETCH: 'RESET_FETCH',
        SUCCESS: 'RESET_FETCH_SUCCESS',
        FAILURE: 'RESET_FETCH_FAILURE',
    },

};


